### PR TITLE
Update gh actions

### PR DESCRIPTION
**Pull request by olivroy**
Use latest github action with usethis::use_github_action("check-standard") and usethis::use_github_action("test-coverage")

### CODE REVIEW

**Comment by alexsanjoseph** [comment]
Hi @olivroy - Sorry for the late response, I was travelling. Thanks for updating, long time pending. One of the actions are failing though, can you figure out why and make a fix for it if possible?

**Comment by alexsanjoseph** [comment]
The following variables are already in the repo 
Screenshot 2023-12-21 at 22 19 53

**Comment by olivroy** [comment]
I do not know. Maybe it is just because I don`t have access, but once you commit to main, it won't be a problem as it will recognize your credentials?

**Comment by alexsanjoseph** [comment]
Seems bizzare, but worth a try. Anyhow already better than what's there, so accepting. Thanks @olivroy

**Comment by alexsanjoseph** [comment]
That actually fixed it, thanks @olivroy for the PR!

**Pull request merged**
